<?php
/**
 * GCODE Parser
 * Extracts metadata from GCODE files (print time, filament, layer height, etc.)
 */

/**
 * Parse GCODE file and extract metadata
 * @param string $filePath Path to GCODE file
 * @return array Extracted metadata
 */
function parseGCodeMetadata($filePath) {
    if (!file_exists($filePath)) {
        return [];
    }

    $metadata = [
        'print_time' => null,
        'print_time_formatted' => null,
        'filament_used' => null,      // in mm
        'filament_used_g' => null,    // in grams
        'filament_used_m' => null,    // in meters
        'layer_height' => null,
        'layer_count' => null,
        'nozzle_diameter' => null,
        'bed_temp' => null,
        'hotend_temp' => null,
        'slicer' => null,
        'slicer_version' => null,
        'print_settings' => null,
        'infill' => null,
        'supports' => null,
    ];

    // Read first 500 lines (metadata is usually at the start) and last 100 lines (some slicers put it at the end)
    $handle = fopen($filePath, 'r');
    if (!$handle) {
        return $metadata;
    }

    $headerLines = [];
    $footerLines = [];
    $lineCount = 0;
    $maxHeaderLines = 500;
    $maxFooterLines = 100;

    // Read header
    while (($line = fgets($handle)) !== false && $lineCount < $maxHeaderLines) {
        $headerLines[] = $line;
        $lineCount++;
    }

    // Read footer (last N lines)
    // Seek to estimate position near end
    $fileSize = filesize($filePath);
    if ($fileSize > 50000) {
        fseek($handle, -50000, SEEK_END);
        fgets($handle); // Skip partial line
    } else {
        rewind($handle);
        // Skip header lines already read
        for ($i = 0; $i < $maxHeaderLines && fgets($handle) !== false; $i++);
    }

    while (($line = fgets($handle)) !== false) {
        $footerLines[] = $line;
        if (count($footerLines) > $maxFooterLines) {
            array_shift($footerLines);
        }
    }

    fclose($handle);

    $allLines = array_merge($headerLines, $footerLines);

    foreach ($allLines as $line) {
        $line = trim($line);

        // Skip non-comment lines
        if (!str_starts_with($line, ';')) {
            continue;
        }

        $line = substr($line, 1); // Remove leading semicolon
        $line = trim($line);

        // PrusaSlicer / OrcaSlicer / SuperSlicer format
        if (preg_match('/^estimated printing time.*?=\s*(.+)$/i', $line, $m)) {
            $metadata['print_time_formatted'] = trim($m[1]);
            $metadata['print_time'] = parseTimeToSeconds($m[1]);
        }
        if (preg_match('/^filament used\s*\[mm\]\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['filament_used'] = (float)$m[1];
        }
        if (preg_match('/^filament used\s*\[g\]\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['filament_used_g'] = (float)$m[1];
        }
        if (preg_match('/^filament used\s*\[m\]\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['filament_used_m'] = (float)$m[1];
        }
        if (preg_match('/^layer_height\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['layer_height'] = (float)$m[1];
        }
        if (preg_match('/^total layers count\s*=\s*(\d+)/i', $line, $m)) {
            $metadata['layer_count'] = (int)$m[1];
        }
        if (preg_match('/^nozzle_diameter\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['nozzle_diameter'] = (float)$m[1];
        }
        if (preg_match('/^bed_temperature\s*=\s*(\d+)/i', $line, $m)) {
            $metadata['bed_temp'] = (int)$m[1];
        }
        if (preg_match('/^temperature\s*=\s*(\d+)/i', $line, $m)) {
            $metadata['hotend_temp'] = (int)$m[1];
        }
        if (preg_match('/^generated by\s+(.+)$/i', $line, $m)) {
            $slicerInfo = trim($m[1]);
            $metadata['slicer'] = $slicerInfo;
            // Try to extract version
            if (preg_match('/^(.+?)\s+([\d.]+.*)$/', $slicerInfo, $vm)) {
                $metadata['slicer'] = trim($vm[1]);
                $metadata['slicer_version'] = trim($vm[2]);
            }
        }
        if (preg_match('/^fill_density\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['infill'] = $m[1] . '%';
        }
        if (preg_match('/^support_material\s*=\s*(\d+)/i', $line, $m)) {
            $metadata['supports'] = $m[1] === '1' ? 'Yes' : 'No';
        }

        // Cura format
        if (preg_match('/^TIME:(\d+)/i', $line, $m)) {
            $metadata['print_time'] = (int)$m[1];
            $metadata['print_time_formatted'] = formatSeconds((int)$m[1]);
        }
        if (preg_match('/^Filament used:\s*([\d.]+)m/i', $line, $m)) {
            $metadata['filament_used_m'] = (float)$m[1];
        }
        if (preg_match('/^Layer height:\s*([\d.]+)/i', $line, $m)) {
            $metadata['layer_height'] = (float)$m[1];
        }
        if (preg_match('/^LAYER_COUNT:(\d+)/i', $line, $m)) {
            $metadata['layer_count'] = (int)$m[1];
        }
        if (preg_match('/^Generated with Cura_SteamEngine\s*([\d.]+)/i', $line, $m)) {
            $metadata['slicer'] = 'Cura';
            $metadata['slicer_version'] = $m[1];
        }

        // Simplify3D format
        if (preg_match('/^Build time:\s*(.+)$/i', $line, $m)) {
            $metadata['print_time_formatted'] = trim($m[1]);
            $metadata['print_time'] = parseTimeToSeconds($m[1]);
        }
        if (preg_match('/^Filament length:\s*([\d.]+)\s*mm/i', $line, $m)) {
            $metadata['filament_used'] = (float)$m[1];
        }

        // Bambu Studio format
        if (preg_match('/^total estimated time:\s*(.+)$/i', $line, $m)) {
            $metadata['print_time_formatted'] = trim($m[1]);
            $metadata['print_time'] = parseTimeToSeconds($m[1]);
        }
        if (preg_match('/^total filament used\s*\[g\]\s*=\s*([\d.]+)/i', $line, $m)) {
            $metadata['filament_used_g'] = (float)$m[1];
        }
    }

    // Convert filament_used (mm) to meters if not already set
    if ($metadata['filament_used'] && !$metadata['filament_used_m']) {
        $metadata['filament_used_m'] = round($metadata['filament_used'] / 1000, 2);
    }

    return $metadata;
}

/**
 * Parse time string to seconds
 * Handles formats like: "1h 30m 45s", "1:30:45", "90 minutes", "1 hour 30 minutes"
 */
function parseTimeToSeconds($timeStr) {
    $timeStr = trim($timeStr);
    $seconds = 0;

    // Format: 1h 30m 45s or 1h30m45s
    if (preg_match_all('/(\d+)\s*([hms])/i', $timeStr, $matches, PREG_SET_ORDER)) {
        foreach ($matches as $match) {
            $value = (int)$match[1];
            $unit = strtolower($match[2]);
            switch ($unit) {
                case 'h': $seconds += $value * 3600; break;
                case 'm': $seconds += $value * 60; break;
                case 's': $seconds += $value; break;
            }
        }
        return $seconds;
    }

    // Format: 1d 2h 30m (days)
    if (preg_match_all('/(\d+)\s*([dhms])/i', $timeStr, $matches, PREG_SET_ORDER)) {
        foreach ($matches as $match) {
            $value = (int)$match[1];
            $unit = strtolower($match[2]);
            switch ($unit) {
                case 'd': $seconds += $value * 86400; break;
                case 'h': $seconds += $value * 3600; break;
                case 'm': $seconds += $value * 60; break;
                case 's': $seconds += $value; break;
            }
        }
        return $seconds;
    }

    // Format: HH:MM:SS or MM:SS
    if (preg_match('/^(\d+):(\d+)(?::(\d+))?$/', $timeStr, $matches)) {
        if (isset($matches[3])) {
            // HH:MM:SS
            return (int)$matches[1] * 3600 + (int)$matches[2] * 60 + (int)$matches[3];
        } else {
            // MM:SS
            return (int)$matches[1] * 60 + (int)$matches[2];
        }
    }

    // Format: "X hours Y minutes" or "X hour Y minute"
    if (preg_match('/(\d+)\s*hours?\s*(?:(\d+)\s*minutes?)?/i', $timeStr, $matches)) {
        $seconds = (int)$matches[1] * 3600;
        if (isset($matches[2])) {
            $seconds += (int)$matches[2] * 60;
        }
        return $seconds;
    }

    // Format: "X minutes" or "X mins"
    if (preg_match('/(\d+)\s*(?:minutes?|mins?)/i', $timeStr, $matches)) {
        return (int)$matches[1] * 60;
    }

    // Just a number (assume seconds)
    if (preg_match('/^\d+$/', $timeStr)) {
        return (int)$timeStr;
    }

    return 0;
}

/**
 * Format seconds to human-readable time
 */
function formatSeconds($seconds) {
    if ($seconds < 60) {
        return $seconds . 's';
    }

    $hours = floor($seconds / 3600);
    $minutes = floor(($seconds % 3600) / 60);
    $secs = $seconds % 60;

    $parts = [];
    if ($hours > 0) {
        $parts[] = $hours . 'h';
    }
    if ($minutes > 0) {
        $parts[] = $minutes . 'm';
    }
    if ($secs > 0 && $hours == 0) {
        $parts[] = $secs . 's';
    }

    return implode(' ', $parts);
}

/**
 * Store GCODE metadata in database
 */
function storeGCodeMetadata($modelId, $metadata) {
    $db = getDB();

    // Check if gcode_metadata table exists, create if not
    if (!tableExists($db, 'gcode_metadata')) {
        $isMysql = (defined('DB_TYPE') && DB_TYPE === 'mysql')
            || $db->getType() === 'mysql';
        if ($isMysql) {
            $db->exec("CREATE TABLE gcode_metadata (
                id INT AUTO_INCREMENT PRIMARY KEY,
                model_id INT NOT NULL UNIQUE,
                print_time INT,
                print_time_formatted TEXT,
                filament_used DOUBLE,
                filament_used_g DOUBLE,
                filament_used_m DOUBLE,
                layer_height DOUBLE,
                layer_count INT,
                nozzle_diameter DOUBLE,
                bed_temp INT,
                hotend_temp INT,
                slicer TEXT,
                slicer_version TEXT,
                infill TEXT,
                supports TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )");
        } else {
            $db->exec("CREATE TABLE gcode_metadata (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                model_id INTEGER NOT NULL UNIQUE,
                print_time INTEGER,
                print_time_formatted TEXT,
                filament_used REAL,
                filament_used_g REAL,
                filament_used_m REAL,
                layer_height REAL,
                layer_count INTEGER,
                nozzle_diameter REAL,
                bed_temp INTEGER,
                hotend_temp INTEGER,
                slicer TEXT,
                slicer_version TEXT,
                infill TEXT,
                supports TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE CASCADE
            )");
        }
    }

    // Insert or update metadata (portable upsert on model_id)
    $checkStmt = $db->prepare('SELECT 1 FROM gcode_metadata WHERE model_id = :model_id');
    $checkStmt->bindValue(':model_id', $modelId, PDO::PARAM_INT);
    $checkStmt->execute();
    $exists = $checkStmt->fetchColumn() !== false;

    if ($exists) {
        $stmt = $db->prepare("UPDATE gcode_metadata SET
            print_time = :print_time,
            print_time_formatted = :print_time_formatted,
            filament_used = :filament_used,
            filament_used_g = :filament_used_g,
            filament_used_m = :filament_used_m,
            layer_height = :layer_height,
            layer_count = :layer_count,
            nozzle_diameter = :nozzle_diameter,
            bed_temp = :bed_temp,
            hotend_temp = :hotend_temp,
            slicer = :slicer,
            slicer_version = :slicer_version,
            infill = :infill,
            supports = :supports
            WHERE model_id = :model_id");
    } else {
        $stmt = $db->prepare("INSERT INTO gcode_metadata
            (model_id, print_time, print_time_formatted, filament_used, filament_used_g, filament_used_m,
             layer_height, layer_count, nozzle_diameter, bed_temp, hotend_temp, slicer, slicer_version, infill, supports)
            VALUES (:model_id, :print_time, :print_time_formatted, :filament_used, :filament_used_g, :filament_used_m,
                    :layer_height, :layer_count, :nozzle_diameter, :bed_temp, :hotend_temp, :slicer, :slicer_version, :infill, :supports)");
    }

    $stmt->bindValue(':model_id', $modelId, PDO::PARAM_INT);
    $stmt->bindValue(':print_time', $metadata['print_time'], PDO::PARAM_INT);
    $stmt->bindValue(':print_time_formatted', $metadata['print_time_formatted'], PDO::PARAM_STR);
    $stmt->bindValue(':filament_used', $metadata['filament_used'], PDO::PARAM_STR);
    $stmt->bindValue(':filament_used_g', $metadata['filament_used_g'], PDO::PARAM_STR);
    $stmt->bindValue(':filament_used_m', $metadata['filament_used_m'], PDO::PARAM_STR);
    $stmt->bindValue(':layer_height', $metadata['layer_height'], PDO::PARAM_STR);
    $stmt->bindValue(':layer_count', $metadata['layer_count'], PDO::PARAM_INT);
    $stmt->bindValue(':nozzle_diameter', $metadata['nozzle_diameter'], PDO::PARAM_STR);
    $stmt->bindValue(':bed_temp', $metadata['bed_temp'], PDO::PARAM_INT);
    $stmt->bindValue(':hotend_temp', $metadata['hotend_temp'], PDO::PARAM_INT);
    $stmt->bindValue(':slicer', $metadata['slicer'], PDO::PARAM_STR);
    $stmt->bindValue(':slicer_version', $metadata['slicer_version'], PDO::PARAM_STR);
    $stmt->bindValue(':infill', $metadata['infill'], PDO::PARAM_STR);
    $stmt->bindValue(':supports', $metadata['supports'], PDO::PARAM_STR);

    return $stmt->execute() !== false;
}

/**
 * Get GCODE metadata for a model
 */
function getGCodeMetadata($modelId) {
    $db = getDB();

    // Check if table exists
    if (!tableExists($db, 'gcode_metadata')) {
        return null;
    }

    $stmt = $db->prepare('SELECT * FROM gcode_metadata WHERE model_id = :model_id');
    $stmt->bindValue(':model_id', $modelId, PDO::PARAM_INT);
    $stmt->execute();
    return $stmt->fetch(PDO::FETCH_ASSOC);
}

/**
 * Parse and store GCODE metadata for a model
 */
function processGCodeFile($modelId, $filePath) {
    $metadata = parseGCodeMetadata($filePath);

    // Only store if we found useful metadata
    $hasData = false;
    foreach ($metadata as $value) {
        if ($value !== null) {
            $hasData = true;
            break;
        }
    }

    if ($hasData) {
        storeGCodeMetadata($modelId, $metadata);
    }

    return $metadata;
}
